### ISSUE TITLE
"php": "^7.4.0||8.1.0||8.2",

### ISSUE THREAD

**Issue by YiffyToys** [anasstouaticoder/magento2-module-referrer-tracker#1]
Are you sure about the PHP requirement ?
PHP 8.1.0 and 8.2 are supported but e.g. 8.1.17 not?

**Comment by anasstouaticoder** [comment]
Hello YiffyToys,
thank you for your comment, normally the module supports all versions from 7.4 to 8.2 ++, it is already tested, i will fix the syntaxe
to  "php": "^7.4 || ^8.0 || ^8.1 || ^8.2"
