### ISSUE TITLE
 Undefined array key "id" in Iterator.php on line 63

### ISSUE THREAD

**Issue by YiffyToys** [anasstouaticoder/magento2-module-referrer-tracker#2]
` main.CRITICAL: Exception: Warning: Undefined array key "id" in ...vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63 `

Could be a wrong tab id in etc/adminhtml/system.xml

**Comment by anasstouaticoder** [comment]
Hello YiffyToys 

can you provide more context, Magento version, php version , how did you install the module (did you use composer) and did you install Base module (anasstouaticoder/magento2-module-base) as well ?

**Comment by YiffyToys** [comment]
Magento 2.4.6 test instance on PH 8.1 via composer.
Crashes when entering the store config page.
Are you by any chance missing a section:
```
         <tab id="anass_Touati_coder" translate="label" sortOrder="1000">
            <label>Anass Touati Coder</label>
        </tab>
```
in system.xml ?

**Comment by anasstouaticoder** [comment]
after switching to an environment Magento 2.4.6-p1 and PHP 8.1, I did not reproduce  your error message, 

I installed the package  : 
in magento project root directory   => composer require anasstouaticoder/magento2-module-referrer-tracker
normally it install 2 packages :

anasstouaticoder/magento2-module-base version 1.2.15

and

anasstouaticoder/magento2-module-referrer-tracker version 1.0.6

after that run in magento project root directory => php bin/magento setup:upgrade 
can you remove the package using command composer remove anasstouaticoder/magento2-module-referrer-tracker  and retry installing it

**Comment by YiffyToys** [comment]
```
Lock file operations: 0 installs, 0 updates, 2 removals
  - Removing anasstouaticoder/magento2-module-base (1.2.15)
  - Removing anasstouaticoder/magento2-module-referrer-tracker (1.0.6)
```


```
>composer require anasstouaticoder/magento2-module-base  1.2.15 anasstouaticoder/magento2-module-referrer-tracker 1.0.6

Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking anasstouaticoder/magento2-module-base (1.2.15)
  - Locking anasstouaticoder/magento2-module-referrer-tracker (1.0.6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing anasstouaticoder/magento2-module-base (1.2.15): Extracting archive
  - Installing anasstouaticoder/magento2-module-referrer-tracker (1.0.6): Extracting archive

>magento setup:upgrade
>magento setup:di:compile 
>magento module:status
...
List of disabled modules:
...
AnassTouatiCoder_Base
AnassTouatiCoder_ReferrerTracker

```

Stores->Settings: Configuration
Works. No "ATOUATI Tools"

```
magento module:enable AnassTouatiCoder_Base
magento module:enable AnassTouatiCoder_ReferrerTracker
magento config:set 'anasstouaticoder_trackreferrerorigin/general/order' 1
magento config:set 'anasstouaticoder_trackreferrerorigin/general/order' 1
magento setup:upgrade
```

Stores->Settings: Configuration

This time it seems to work despite the exact same version numbers of both modules as before.
